name = "ticker-backend-worker2"
main = "src/simple-index.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
TICKER_API_BASE_URL = "https://ticker-backend-3a6tr24j5-thilinas-projects-f6f25033.vercel.app"
TICKER_API_KEY = "tk_demo_key_12345"

# Simple cron trigger (no queue yet)
[[triggers.crons]]
cron = "0 9,21 * * *"

# Production environment
[env.production]
[env.production.vars]
TICKER_API_BASE_URL = "https://ticker-backend-3a6tr24j5-thilinas-projects-f6f25033.vercel.app"
TICKER_API_KEY = "tk_demo_key_12345"

# Development environment  
[env.development]
[env.development.vars]
TICKER_API_BASE_URL = "https://ticker-backend-3a6tr24j5-thilinas-projects-f6f25033.vercel.app"
TICKER_API_KEY = "tk_demo_key_12345"