name = "ticker-backend-worker-simple"
main = "src/stage4-index.js"
compatibility_date = "2024-08-01"
compatibility_flags = ["nodejs_compat"]

# Default environment variables
[vars]
TICKER_API_BASE_URL = "https://ticker-backend-nu.vercel.app"
TICKER_API_KEY = "tk_demo_key_12345"
SUPABASE_URL = "https://cdvskimffubkppnyipjc.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdnNraW1mZnVia3BwbnlpcGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTAwNDksImV4cCI6MjA3MDQ2NjA0OX0.dEtTfbzDfFmP2wJH-TosngTj9useLGwKW3l_xTWDk7o"
POLYGON_API_KEY = "lAAH5udcnYQYFnGVglymuhwwDodBGD1L"

# Authentication configuration
WORKER_AUTH_ENABLED = "true"
WORKER_RATE_LIMIT = "100"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

# Cloudflare Queue for instant new ticker processing
[[queues.producers]]
binding = "TICKER_QUEUE"
queue = "ticker-dividend-queue"

[[queues.consumers]]
queue = "ticker-dividend-queue"
max_batch_size = 5
max_batch_timeout = 5
max_retries = 3

# Cron triggers for bulk dividend updates (twice daily)
[triggers]
crons = ["0 9,21 * * *"]

# Production environment (optional override)
[env.production]
[env.production.vars]
TICKER_API_BASE_URL = "https://ticker-backend-nu.vercel.app"
TICKER_API_KEY = "tk_demo_key_12345"
SUPABASE_URL = "https://cdvskimffubkppnyipjc.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdnNraW1mZnVia3BwbnlpcGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4OTAwNDksImV4cCI6MjA3MDQ2NjA0OX0.dEtTfbzDfFmP2wJH-TosngTj9useLGwKW3l_xTWDk7o"
POLYGON_API_KEY = "lAAH5udcnYQYFnGVglymuhwwDodBGD1L"
WORKER_AUTH_ENABLED = "true"
WORKER_RATE_LIMIT = "100"

# Development environment (optional override)
[env.development]
[env.development.vars]
TICKER_API_BASE_URL = "https://ticker-backend-nu.vercel.app"
TICKER_API_KEY = "tk_demo_key_12345"
WORKER_AUTH_ENABLED = "true"
WORKER_RATE_LIMIT = "50"
